#!/usr/bin/env bash
# installs and configures haproxy as a round robin load balancer for web-01 and web-02
apt-get update -y
apt-get install -y haproxy
cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7079-web-01 3.82.243.210:80 check
    server 7079-web-02 18.212.191.191:80 check
EOF
service haproxy restart
